email: contact@example.org  
linkedin: https://linkedin.com/example
twitter: https://twitter.com/example
facebook: https://facebook.com/example
name: Acme Corporation
location: New York
phone: (999) 999-9999
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
