# main:
#   - identifier: about
#     name: About
#     url: /about
#     weight: 1
#   - identifier: blog
#     name: Blog
#     url: /blog
#     weight: 2
#   - identifier: news
#     name: News
#     url: /news
#     weight: 3
#   - identifier: contact
#     name: Contact
#     url: /contact
#     weight: 4

