main:
- identifier: about
  name: About
  url: /about
  weight: 1
- identifier: blog
  name: Blog
  url: /blog
  weight: 2
- identifier: community
  name: Community
  parent: blog  
  url: /blog/community
- identifier: news
  name: News
  url: /news
  weight: 3
- identifier: contact
  name: Contact
  url: /contact
  weight: 4
    
footer:
- identifier: blog
  name: Blog
  url: /blog
  weight: 1
- identifier: categories
  name: Categories
  url: /categories
  weight: 2
- identifier: terms
  name: Terms of Use
  url: /terms
  weight: 3
- identifier: privacy
  name: Privacy Policy
  url: /privacy
  weight: 4
- identifier: credits
  name: Credits
  url: /credits
  weight: 5
