main:
- identifier: about
  name: About
  url: /about
  weight: 10
- identifier: blog
  name: Blog
  url: /blog
  weight: 20
- identifier: community
  name: Community
  parent: blog  
  url: /blog/community
- identifier: news
  name: News
  url: /news
  weight: 30
- identifier: contact
  name: Contact
  url: /contact
  weight: 40
    
footer:
- identifier: categories
  name: Categories
  url: /categories
  weight: 20
- identifier: survey
  name: Surveys
  url: /survey
  weight: 30
- identifier: terms
  name: Terms of Use
  url: /terms
  weight: 40
- identifier: privacy
  name: Privacy Policy
  url: /privacy
  weight: 50
- identifier: credits
  name: Credits
  url: /credits
  weight: 60
