baseURL: /
languageCode: en-us
title: Acme Corporation
theme: Eclectic
author:
  email: contact@example.org  
  linkedin: https://linkedin.com/example
  twitter: https://twitter.com/example
  facebook: https://facebook.com/example
  name: Acme Corporation
  location: New York
  phone: (999) 999-9999
  hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
menu:
  main:
    - identifier: about
      name: About Us
      url: /about
      weight: 1
    - identifier: privacy
      name: Privacy Policy
      url: /privacy
      weight: 2
    - identifier: terms
      name: Terms of Use
      url: /terms
      weight: 3
    - identifier: contact
      name: Contact Us
      url: /contact
      weight: 4
params:
  color: "#4f46e5" # warning: color must be quoted because of leading # == comment
  custom_css: [./css/custom.css]
  copyright: Copyright &copy; Acme Corporation&trade;, 1990-2021. All Rights Reserved.
  footer:
    - title: About
      content: >
        Acme Corporation is the world's leading
        manufacturer of digital shapes. From squares and
        circles to triangles and hexagons, we have it
        all. Browse through our collection of various
        forms with different thicknesses and line styles.
        We shape the world. You live in it.
    - title: Recent Posts
      recents: blog
      recentCount: 6
    - title: Contact Us
      contact: true
  style: blue
  logo: /image/logo.png
  logo_small: /image/logo.png
  about_us: >
    Acme Corporation is the world's leading manufacturer 
    of digital shapes. From squares and circles to 
    triangles and hexagons, we have it all. Browse through 
    our collection of various forms with different 
    thicknesses and line styles. We shape the world. 
    You live in it.
  recent_posts:
    enable: true
markup:
  goldmark:
    renderer:
      unsafe: false # allow HTML within Markdown eg <mark>highlight</mark>
  highlight:
    lineNos: true # line numbers in ```code```
enableEmoji: true # convert :emoji: 

